pins:
  - pin: 9
    id: MSIOBOX_0_OUT_1
    class: outputs
    ts_name: MS IO-Box 0 OUT 1

  - pin: 10
    id: MSIOBOX_0_OUT_2
    class: outputs
    ts_name: MS IO-Box 0 OUT 2

  - pin: 7
    id: MSIOBOX_0_OUT_3
    class: outputs
    ts_name: MS IO-Box 0 OUT 3

  - pin: 8
    id: MSIOBOX_0_OUT_4
    class: outputs
    ts_name: MS IO-Box 0 OUT 4

info:
  cid: iobox
