package com.rusefi.enums;
// based on ./controllers/algo/engine_types.h
//auto-generated by ToJavaEnum.java



public enum drive_train_layout_e {
	DRIVETRAIN_NONE,
	DRIVETRAIN_RWD,
	DRIVETRAIN_FWD,
	DRIVETRAIN_AWD,
}
