meta: config/boards/M144H7BLACK/M144_meta.h

pins:
- class: outputs
  meta: M144_D0
  pin: 0
  ts_name: D0
  type: ls
- class: outputs
  meta: M144_D1
  pin: 1
  ts_name: D1
  type: ls
- class: outputs
  meta: M144_D2
  pin: 2
  ts_name: D2
  type: ls
- class: outputs
  meta: M144_D3
  pin: 3
  ts_name: D3
  type: ls
- class: outputs
  meta: M144_D4
  pin: 4
  ts_name: D4
  type: ls
- class: outputs
  meta: M144_D5
  pin: 5
  ts_name: D5
  type: ls
- class: outputs
  meta: M144_D6
  pin: 6
  ts_name: D6
  type: ls
- class: outputs
  meta: M144_D7
  pin: 7
  ts_name: D7
  type: ls
- class: outputs
  meta: M144_D8
  pin: 8
  ts_name: D8
  type: ls
- class: outputs
  meta: M144_D9
  pin: 9
  ts_name: D9
  type: ls
- class: outputs
  meta: M144_D10
  pin: 10
  ts_name: D10
  type: ls
- class: outputs
  meta: M144_D11
  pin: 11
  ts_name: D11
  type: ls
- class: outputs
  meta: M144_D12
  pin: 12
  ts_name: D12
  type: ls
- class: outputs
  meta: M144_D13
  pin: 13
  ts_name: D13
  type: ls
- class: outputs
  meta: M144_D14
  pin: 14
  ts_name: D14
  type: ls
- class: outputs
  meta: M144_D15
  pin: 15
  ts_name: D15
  type: ls
- class: outputs
  meta: M144_D16
  pin: 16
  ts_name: D16
  type: ls
- class: outputs
  meta: M144_D17
  pin: 17
  ts_name: D17
  type: ls
- class: outputs
  meta: M144_D18
  pin: 18
  ts_name: D18
  type: ls
- class: outputs
  meta: M144_D19
  pin: 19
  ts_name: D19
  type: ls
- class: outputs
  meta: M144_D20
  pin: 20
  ts_name: D20
  type: ls
- class: outputs
  meta: M144_D21
  pin: 21
  ts_name: D21
  type: ls
- class: outputs
  meta: M144_D22
  pin: 22
  ts_name: D22
  type: ls
- class: outputs
  meta: M144_D23
  pin: 23
  ts_name: D23
  type: ls
- class: outputs
  meta: M144_D24
  pin: 24
  ts_name: D24
  type: ls
- class: outputs
  meta: M144_D25
  pin: 25
  ts_name: D25
  type: ls
- class: outputs
  meta: M144_D26
  pin: 26
  ts_name: D26
  type: ls
- class: outputs
  meta: M144_D27
  pin: 27
  ts_name: D27
  type: ls
- class: outputs
  meta: M144_D28
  pin: 28
  ts_name: D28
  type: ls
- class: outputs
  meta: M144_D29
  pin: 29
  ts_name: D29
  type: ls
- class: outputs
  meta: M144_D30
  pin: 30
  ts_name: D30
  type: ls
- class: outputs
  meta: M144_D31
  pin: 31
  ts_name: D31
  type: ls
- class: outputs
  meta: M144_D32
  pin: 32
  ts_name: D32
  type: ls
- class: outputs
  meta: M144_D33
  pin: 33
  ts_name: D33
  type: ls
- class: outputs
  meta: M144_D34
  pin: 34
  ts_name: D34
  type: ls
- class: outputs
  meta: M144_D35
  pin: 35
  ts_name: D35
  type: ls
- class: outputs
  meta: M144_D36
  pin: 36
  ts_name: D36
  type: ls
- class: outputs
  meta: M144_D37
  pin: 37
  ts_name: D37
  type: ls
- class: outputs
  meta: M144_D38
  pin: 38
  ts_name: D38
  type: ls
- class: outputs
  meta: M144_D39
  pin: 39
  ts_name: D39
  type: ls
- class: outputs
  meta: M144_D40
  pin: 40
  ts_name: D40
  type: ls
- class: outputs
  meta: M144_D41
  pin: 41
  ts_name: D41
  type: ls
- class: outputs
  meta: M144_D42
  pin: 42
  ts_name: D42
  type: ls
- class: outputs
  meta: M144_D43
  pin: 43
  ts_name: D43
  type: ls
- class: outputs
  meta: M144_D44
  pin: 44
  ts_name: D44
  type: ls
- class: outputs
  meta: M144_D45
  pin: 45
  ts_name: D45
  type: ls
- class: outputs
  meta: M144_D46
  pin: 46
  ts_name: D46
  type: ls
- class: outputs
  meta: M144_D47
  pin: 47
  ts_name: D47
  type: ls
- class: outputs
  meta: M144_D48
  pin: 48
  ts_name: D48
  type: ls
- class: outputs
  meta: M144_D49
  pin: 49
  ts_name: D49
  type: ls
- class: outputs
  meta: M144_D50
  pin: 50
  ts_name: D50
  type: ls
- class: outputs
  meta: M144_D51
  pin: 51
  ts_name: D51
  type: ls
- class: outputs
  meta: M144_D52
  pin: 52
  ts_name: D52
  type: ls
- class: outputs
  meta: M144_D53
  pin: 53
  ts_name: D53
  type: ls
- class: analog_inputs
  meta: M144_A0
  pin: 54
  ts_name: A0
  type: av
- class: analog_inputs
  meta: M144_A1
  pin: 55
  ts_name: A1
  type: av
- class: analog_inputs
  meta: M144_A2
  pin: 56
  ts_name: A2
  type: av
- class: analog_inputs
  meta: M144_A3
  pin: 57
  ts_name: A3
  type: av
- class: analog_inputs
  meta: M144_A4
  pin: 58
  ts_name: A4
  type: av
- class: analog_inputs
  meta: M144_A5
  pin: 59
  ts_name: A5
  type: av
- class: analog_inputs
  meta: M144_A6
  pin: 60
  ts_name: A6
  type: av
- class: analog_inputs
  meta: M144_A7
  pin: 61
  ts_name: A7
  type: av
- class: analog_inputs
  meta: M144_A8
  pin: 62
  ts_name: A8
  type: av
- class: analog_inputs
  meta: M144_A9
  pin: 63
  ts_name: A9
  type: av
- class: analog_inputs
  meta: M144_A10
  pin: 64
  ts_name: A10
  type: av
- class: analog_inputs
  meta: M144_A11
  pin: 65
  ts_name: A11
  type: av
- class: analog_inputs
  meta: M144_A12
  pin: 66
  ts_name: A12
  type: av
- class: analog_inputs
  meta: M144_A13
  pin: 67
  ts_name: A13
  type: av
- class: analog_inputs
  meta: M144_A14
  pin: 68
  ts_name: A14
  type: av
- class: analog_inputs
  meta: M144_A15
  pin: 69
  ts_name: A15
  type: av
